from custom_diffusion.pipelines.controlnet_inpaint_pipeline import StableDiffusionControlNetInpaintGenerator
from custom_diffusion.pipelines.controlnet_pipeline import StableDiffusionControlNetGenerator

__version__ = "0.1.4"
